version: "3.7"
services:
  flask-app:
    image: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - "./flask:/app"
    command: ["python", "app.py"]
  express-app:
    image: express
    build:
      context: ./express
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      FLASK_SERVICE: flask-app:5000
    ports:
      - 8000:8000
    volumes:
      - "./express:/app"
    command: ["npm", "start"]
