name: Flask CI/CD

on:
  push:
    paths: 
      - flask/**
      - .github/workflows/flask-workflow.yml
    branches: [ main ]

jobs:
  ci-flask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
        architecture: x64
    - name: dependencies
      run: pip install -r requirement.txt
      working-directory: ./flask
    - name: linter
      run: flake8 --statistics
      working-directory: ./flask
    - name: test
      run: pytest -v --cov=app
      working-directory: ./flask

# Todo : CD with Heroku
